// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace PrimeVsZombieDB {
    using PrimeVsZombieDB;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    
    
    public class GamePlaySceneBase : uFrame.Kernel.Scene {
        
        public override string DefaultKernelScene {
            get {
                return "PrimeVsZombieDBKernelScene";
            }
        }
        
        public virtual GamePlaySceneSettings Settings {
            get {
                return _SettingsObject as GamePlaySceneSettings;
            }
            set {
                _SettingsObject = value;
            }
        }
    }
}
