// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace PrimeVsZombieDB {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    
    
    public class ZombieControllerBase : uFrame.MVVM.Controller {
        
        private uFrame.MVVM.ViewModels.IViewModelManager _ZombieViewModelManager;
        
        private PrimeViewModel _Prime;
        
        private GamePlayViewModel _GamePlay;
        
        [uFrame.IOC.InjectAttribute("Zombie")]
        public uFrame.MVVM.ViewModels.IViewModelManager ZombieViewModelManager {
            get {
                return _ZombieViewModelManager;
            }
            set {
                _ZombieViewModelManager = value;
            }
        }
        
        [uFrame.IOC.InjectAttribute("Prime")]
        public PrimeViewModel Prime {
            get {
                return _Prime;
            }
            set {
                _Prime = value;
            }
        }
        
        [uFrame.IOC.InjectAttribute("GamePlay")]
        public GamePlayViewModel GamePlay {
            get {
                return _GamePlay;
            }
            set {
                _GamePlay = value;
            }
        }
        
        public IEnumerable<ZombieViewModel> ZombieViewModels {
            get {
                return ZombieViewModelManager.OfType<ZombieViewModel>();
            }
        }
        
        public override void Setup() {
            base.Setup();
            // This is called when the controller is created
        }
        
        public override void Initialize(uFrame.MVVM.ViewModels.ViewModel viewModel) {
            base.Initialize(viewModel);
            // This is called when a viewmodel is created
            this.InitializeZombie(((ZombieViewModel)(viewModel)));
        }
        
        public virtual ZombieViewModel CreateZombie() {
            return ((ZombieViewModel)(this.Create(Guid.NewGuid().ToString())));
        }
        
        public override uFrame.MVVM.ViewModels.ViewModel CreateEmpty() {
            return new ZombieViewModel(this.EventAggregator);
        }
        
        public virtual void InitializeZombie(ZombieViewModel viewModel) {
            // This is called when a ZombieViewModel is created
            ZombieViewModelManager.Add(viewModel);
        }
        
        public override void DisposingViewModel(uFrame.MVVM.ViewModels.ViewModel viewModel) {
            base.DisposingViewModel(viewModel);
            ZombieViewModelManager.Remove(viewModel);
        }
    }
}
