// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace PrimeVsZombieDB {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Kernel;
    using uFrame.Kernel.Serialization;
    using uFrame.MVVM;
    
    
    public partial class MoveDownCommand : uFrame.MVVM.ViewModels.ViewModelCommand {
    }
    
    public partial class MoveRightCommand : uFrame.MVVM.ViewModels.ViewModelCommand {
    }
    
    public partial class MoveUpCommand : uFrame.MVVM.ViewModels.ViewModelCommand {
    }
    
    public partial class MoveStopCommand : uFrame.MVVM.ViewModels.ViewModelCommand {
    }
    
    public partial class MoveLeftCommand : uFrame.MVVM.ViewModels.ViewModelCommand {
    }
}
